sets.exported = {
    main="Bunzi's Rod",
    sub="Genbu's Shield",
    range="Dunna",
    head="Null Masque",
    body="Azimuth Coat +2",
    hands="Nyame Gauntlets",
    legs="Volte Brais",
    feet="Geo. Sandals +3",
    neck="Loricate Torque +1",
    waist="Null Belt",
    left_ear="Alabaster Earring",
    right_ear={ name="Azimuth Earring +1", augments={'System: 1 ID: 1676 Val: 0','Mag. Acc.+14','Damage taken-5%',}},
    left_ring="Murky Ring",
    right_ring="Defending Ring",
    back={ name="Nantosuelta's Cape", augments={'INT+8','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
}