sets.exported = {
    main="Bunzi's Rod",
    sub="Genbu's Shield",
    range="Dunna",
    head="Null Masque",
    body="Gyve Doublet",
    hands="Nyame Gauntlets",
    legs="Gyve Trousers",
    feet="Nyame Sollerets",
    neck="Loricate Torque +1",
    waist="Null Belt",
    left_ear="Alabaster Earring",
    right_ear={ name="Azimuth Earring +1", augments={'System: 1 ID: 1676 Val: 0','Mag. Acc.+14','Damage taken-5%',}},
    left_ring="Gelatinous Ring +1",
    right_ring="Kishar Ring",
    back="Null Shawl",
}