sets.exported = {
    main={ name="Solstice", augments={'INT+15','"Mag.Atk.Bns."+10','"Refresh"+1',}},
    sub="Levante Dagger",
    range="Dunna",
    head="Null Masque",
    body="Azimuth Coat +2",
    hands="Nyame Gauntlets",
    legs="Volte Brais",
    feet="Geo. Sandals +3",
    neck="Loricate Torque +1",
    waist="Null Belt",
    left_ear="Alabaster Earring",
    right_ear={ name="Azimuth Earring +1", augments={'System: 1 ID: 1676 Val: 0','Mag. Acc.+14','Damage taken-5%',}},
    left_ring="Murky Ring",
    right_ring="Defending Ring",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +10','Indi. eff. dur. +13','Pet: Damage taken -2%',}},
}