sets.exported = {
    main="Naegling",
    sub="Demers. Degen +1",
    range="Molybdosis",
    ammo="Orichalc. Bullet",
    head="Null Masque",
    body="Malignance Tabard",
    hands="Lak. Gants +4",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Malignance Boots",
    neck="Null Loop",
    waist="Reiki Yotai",
    left_ear="Alabaster Earring",
    right_ear="Dedition Earring",
    left_ring="Defending Ring",
    right_ring="Murky Ring",
    back="Null Shawl",
}