sets.exported = {
    main="Excalibur",
    sub="Duban",
    ammo="Homiliary",
    head="Rev. Coronet +3",
    body="Rev. Surcoat +3",
    hands="Rev. Gauntlets +3",
    legs="Rev. Breeches +3",
    feet="Rev. Leggings +3",
    neck="Unmoving Collar +1",
    waist="Plat. Mog. Belt",
    left_ear="Odnowa Earring",
    right_ear="Alabaster Earring",
    left_ring="Murky Ring",
    right_ring="Gelatinous Ring +1",
    back={ name="Rudianos's Mantle", augments={'VIT+7','Eva.+20 /Mag. Eva.+20','Mag. Evasion+5','Enmity+10','Phys. dmg. taken-10%',}},
}