---@diagnostic disable: undefined-global
-- Gear inventory for Brooksthewitch
-- Returns a table of gear pieces referenced across job files

return {
    -- Weapons / Instruments
    Trial_Wand           = "Trial Wand",
    Kaja_Rod             = "Kaja Rod",
    Tokko_Sword          = "Tokko Sword",
    Malignance_Pole      = "Malignance Pole",

    -- Range / Ammo
    Filiae_Bell          = "Filiae Bell",
    Dunna                = "Dunna",
    Matre_Bell           = "Matre Bell",
    Yamarang             = "Yamarang",
    Knobkierrie          = "Knobkierrie",
    Ginsen               = "Ginsen",

    -- Sub
    Niobid_Strap         = "Niobid Strap",
    Utu_Grip             = "Utu Grip",
    Enki_Strap           = "Enki Strap",
    Diamond_Aspis        = "Diamond Aspis",
    Adapa_Shield         = "Adapa Shield",
    Ammurapi_Shield      = "Ammurapi Shield",
    Culminus             = "Culminus",
    Genmei_Shield        = "Genmei Shield",
    Koboto               = "Koboto",

    -- Head
    Merl_Hood_FC         = { name = "Merlinic Hood", augments = { '"Fast Cast"+5', 'INT+5', 'Mag. Acc.+7', '"Mag.Atk.Bns."+4', } },
    Bagua_Galero         = { name = "Bagua Galero", augments = { 'Enhances "Primeval Zeal" effect', } },
    Geomancy_Galero      = "Geo. Galero +1",
    Azimuth_Hood         = "Azimuth Hood +2",
    Sukeroku_Hachi       = "Sukeroku Hachi.",
    Jhakri_Coronal       = "Jhakri Coronal +2",
    Aya_Zucchetto        = "Aya. Zucchetto +2",
    Orvail_Corona        = "Orvail Corona +1",
    Tema_Headband        = "Tema. Headband",
    Decennial_Tiara      = "Decennial Tiara",
    Redeyes              = "Redeyes",
    Behe_Masque          = "Behe. Masque +1",
    Goblin_Masque        = "Goblin Masque",
    GMoogle_Masque       = "G. Moogle Masque",

    -- Neck
    Bagua_Charm          = "Bagua Charm +1",
    Erra_Pendant         = "Erra Pendant",
    Nodens_Gorget        = "Nodens Gorget",
    Jokushu_Chain        = "Jokushu Chain",
    Adad_Amulet          = "Adad Amulet",
    Loricate_torque      = "Loricate Torque +1",
    Quanpur_Necklace     = "Quanpur Necklace",
    Mizu_Kubikazari      = "Mizu. Kubikazari",
    Nicander_Necklace    = "Nicander's Necklace",

    -- Ears
    Kyrenes_Earring      = "Kyrene's Earring",
    Raising_Earring      = "Raising Earring",
    Domin_Earring        = "Domin. Earring +1",
    Unkai_Mimikazari     = "Unkai Mimikazari",
    Brutal_Earring       = "Brutal Earring",
    Alabaster_Earring    = "Alabaster Earring",
    Loquac_Earring       = "Loquac. Earring",
    Sortiarius_Earring   = "Sortiarius Earring",
    Lugalbanda_Earring   = "Lugalbanda Earring",
    Kasuga_Earring       = { name = "Kasuga Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+9', 'Mag. Acc.+9', } },
    Azimuth_Earring      = { name = "Azimuth Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Mag. Acc.+8', } },
    Hashishin_Earring    = { name = "Hashishin Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+10', 'Mag. Acc.+10', } },
    Chas_Earring         = { name = "Chas. Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+9', 'Mag. Acc.+9', } },
    Pel_Earring          = { name = "Pel. Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+11', 'Mag. Acc.+11', 'Crit.hit rate+3', } },
    Nourish_Earring      = "Nourish. Earring",

    -- Body
    Merl_Jubbah_FC       = { name = "Merlinic Jubbah", augments = { '"Mag.Atk.Bns."+15', '"Fast Cast"+5', 'CHR+5', } },
    Bagua_Tunic          = { name = "Bagua Tunic", augments = { 'Enhances "Bolster" effect', } },
    Vanya_Robe           = { name = "Vanya Robe", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Geomancy_Tunic       = "Geomancy Tunic +2",
    Jhakri_Robe          = "Jhakri Robe +2",
    Ayanmo_Corazza       = "Ayanmo Corazza +2",
    Orvail_Robe          = "Orvail Robe +1",
    Odyss_Chestplate     = "Odyss. Chestplate",
    Councilor_Garb       = "Councilor's Garb",
    MG_Bodice            = "MG Bodice +1",
    Azimuth_Coat         = "Azimuth Coat +1",
    Atrophy_Tabard       = "Atrophy Tabard +3",
    Temachtiani_Shirt    = "Temachtiani Shirt",
    Novennial_Dress      = "Novennial Dress",
    Decennial_Dress      = "Decennial Dress",
    Goblin_Suit          = "Goblin Suit",
    GMoogle_Suit         = "G. Moogle Suit",
    Gyve_Doublet         = "Gyve Doublet",

    -- Hands
    Bagua_Mitaines       = { name = "Bagua Mitaines", augments = { 'Enhances "Curative Recantation" effect', } },
    Vanya_Cuffs          = { name = "Vanya Cuffs", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Geomancy_Mitaines    = "Geo. Mitaines +2",
    Jhakri_Cuffs         = "Jhakri Cuffs +2",
    Aya_Manopolas        = "Aya. Manopolas +2",
    -- Vanya_Cuffs          = "Vanya Cuffs",
    Onimusha_Kote        = "Onimusha-no-Kote",
    Merl_Dastanas        = "Merlinic Dastanas",
    MG_Gloves            = "MG Gloves +1",
    Azimuth_Gloves       = "Azimuth Gloves +2",
    Leyline_Gloves       = { name = "Leyline Gloves", augments = { 'Accuracy+6', 'Mag. Acc.+2', '"Mag.Atk.Bns."+6', } },
    Temachtiani_Gloves   = "Temachtiani Gloves",
    Councilor_Cuffs      = "Councilor's Cuffs",
    Bards_Cuffs          = "Bard's Cuffs",
    Duelists_Gloves      = "Duelist's Gloves",

    -- Rings
    Dim_Ring_Dem         = "Dim. Ring (Dem)",
    Dingir_Ring          = "Dingir Ring",
    Hetairoi_Ring        = "Hetairoi Ring",
    Jhakri_Ring          = "Jhakri Ring",
    Jubilee_Ring         = "Jubilee Ring",
    Warp_Ring            = "Warp Ring",
    Echad_Ring           = "Echad Ring",
    Empress_Band         = "Empress Band",
    Facility_Ring        = "Facility Ring",
    Caliber_Ring         = "Caliber Ring",
    Murky_Ring           = "Murky Ring",
    Shneddick_Ring       = "Shneddick Ring",
    Dcl_Grd_Ring         = "Dcl.Grd. Ring",

    -- Back
    Nantosuelta_Cape_FC  = { name = "Nantosuelta's Cape", augments = { '"Fast Cast"+10', } },
    Nantosuelta_Cape_Pet = { name = "Nantosuelta's Cape", augments = { 'HP+30', 'Eva.+10 /Mag. Eva.+10', 'Mag. Evasion+3', 'Pet: "Regen"+10', 'Damage taken-5%', } },
    Nantosuelta_Cape     = "Nantosuelta's Cape",
    Nexus_Cape           = "Nexus Cape",
    Alabaster_Mantle     = "Alabaster Mantle",

    -- Waist
    Olympus_Sash         = "Olympus Sash",
    Flume_Belt           = "Flume Belt",
    Sailfi_Belt          = "Sailfi Belt +1",
    Embla_Sash           = "Embla Sash",
    Isa_Belt             = "Isa Belt",

    -- Legs
    Bagua_Pants          = { name = "Bagua Pants +4", augments = { 'Enhances "Mending Halation" effect', } },
    Vanya_Slops          = { name = "Vanya Slops", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Geomancy_Pants       = "Geo. Pants +1",
    Jhakri_Slops         = "Jhakri Slops +2",
    Ayanmo_Cosciales     = "Ayanmo Cosciales",
    Hercl_Trousers       = "Herculean Trousers",
    Rawhide_Trousers     = "Rawhide Trousers",
    Assid_Pants          = "Assid. Pants +1",
    MGF_Chausses         = "MGF Chausses +1",
    Temachtiani_Pants    = "Temachtiani Pants",
    Decennial_Hose       = "Decennial Hose",
    Novennial_Boots      = "Novennial Boots",
    Sorcerer_Tonban      = "Sorcerer's Tonban",
    Wyrm_Brais           = "Wyrm Brais",
    Estqr_Fuseau         = "Estqr. Fuseau +1",
    Aya_Cosciales        = "Aya. Cosciales +1",
    Azimuth_Tights       = "Azimuth Tights +1",

    -- Feet
    Merl_Crackows_FC     = { name = "Merlinic Crackows", augments = { 'Mag. Acc.+15', '"Fast Cast"+6', 'CHR+15', } },
    Merl_Crackows_Pet    = { name = "Merlinic Crackows", augments = { 'Pet: Attack+21 Pet: Rng.Atk.+21', 'INT+3', '"Refresh"+1', } },
    Bagua_Sandals        = { name = "Bagua Sandals +4", augments = { 'Enhances "Radial Arcana" effect', } },
    Vanya_Clogs          = { name = "Vanya Clogs", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Geomancy_Sandals     = "Geo. Sandals +3",
    Aya_Gambieras        = "Aya. Gambieras",
    Jhakri_Pigaches      = "Jhakri Pigaches +2",
    Odyssean_Greaves     = "Odyssean Greaves",
    MGF_Ledelsens        = "MGF Ledelsens +1",
    Battlecast_Gaiters   = "Battlecast Gaiters",
    Azimuth_Gaiters      = "Azimuth Gaiters +2",
    Temachtiani_Boots    = "Temachtiani Boots",
    Sprinters_Shoes      = "Sprinter's Shoes",
    Comm_Bottes          = "Comm. Bottes",
    Melee_Gaiters        = "Melee Gaiters",
    Abyss_Sollerets      = "Abyss Sollerets",
}
