local equipment = {
    RAbullet               = "Chrono Bullet",
    RAccbullet             = "Chrono Bullet",
    WSbullet               = "Chrono Bullet",
    MAbullet               = "Living Bullet",
    QDbullet               = "Hauksbok Bullet",

    anchorite_head         = "Anch. Crown +3",
    anchorite_body         = "Anch. Cyclas +3",
    anchorite_hands        = "Anchor. Gloves +3",
    anchorite_legs         = "Anch. Hose +3",
    anchorite_feet         = "Anch. Gaiters +3",

    bhikku_crown           = "Bhikku Crown +2",
    bhikku_body            = "Bhikku Cyclas +3",
    bhikku_gloves          = "Bhikku Gloves +2",
    bhikku_hose            = "Bhikku Hose +3",
    bhikku_feet            = "Bhikku Gaiters +2",

    hesychast_crown        = "Hes. Crown",
    hesychast_body         = "Hes. Cyclas",
    hesychast_gloves       = "Hes. Gloves",
    hesychast_hose         = "Hes. Hose",
    hesychast_feet         = "Hes. Gaiters",

    telchine_cap_regen     = { name = "Telchine Cap", augments = { '"Regen" potency+3', } },
    telchine_gloves_regen  = { name = "Telchine Gloves", augments = { '"Regen" potency+3', } },
    telchine_body_regen    = { name = "Telchine Chas.", augments = { '"Regen" potency+3', } },
    telchine_legs_regen    = { name = "Telchine Braconi", augments = { '"Regen" potency+3', } },
    telchine_feet_enh_dur  = { name = "Telchine Pigaches", augments = { '"Cure" potency +1%', 'Enh. Mag. eff. dur. +10', } },

    --head
    Herc_TA_head           = { name = "Herculean Helm", augments = { '"Triple Atk."+4', 'STR+2', 'Accuracy+15', 'Attack+12', } },
    Herc_WS_head           = { name = "Herculean Helm", augments = { 'Accuracy+10 Attack+10', 'Weapon skill damage +5%', 'DEX+6', } },
    Herc_MAB_head          = { name = "Herculean Helm", augments = { 'Mag. Acc.+19 "Mag.Atk.Bns."+19', 'Magic burst dmg.+3%', 'INT+8', '"Mag.Atk.Bns."+13', } },
    malignance_chapeau     = "Malignance Chapeau",
    Lanun_tricorne         = "Lanun Tricorne",
    meghanda_head          = "Meghanada Visor +2",
    taeon_head_phalanx     = { name = "Taeon Chapeau", augments = { 'Accuracy+20 Attack+20', '"Triple Atk."+2', 'Phalanx +3', } },
    phalanx_head           = { name = "Chironic Hat", augments = { '"Fast Cast"+1', 'Accuracy+18', 'Phalanx +4', 'Accuracy+3 Attack+3', } },
    white_rarab_cap        = "Wh. Rarab Cap +1",
    oshosi_mask            = "Oshosi Mask",
    vitiation_chapeau      = { name = "Viti. Chapeau +4", augments = { 'Enfeebling Magic duration', 'Magic Accuracy', } },
    blistering_sallet      = { name = "Blistering Sallet +1", augments = { 'Path: A', } },
    chasseurs_tricorne     = "Chass. Tricorne +2",
    hashishin_head         = "Hashishin Kavuk +3",
    lethargy_chappel       = "Leth. Chappel +3",
    null_mask              = "Null Masque",
    ea_hat                 = "Ea Hat +1",
    pixie_hairpin          = "Pixie Hairpin +1",
    hjarrandi_helm         = "Hjarrandi Helm",
    flama_head             = "Flam. Zucchetto +2",
    agoge_mask             = { name = "Agoge Mask +4", augments = { 'Enhances "Savagery" effect', } },
    pummler_mask           = "Pummeler's Mask +1",
    boii_mask              = "Boii Mask +2",
    luhlaza_head           = { name = "Luh. Keffiyeh +2", augments = { 'Enhances "Convergence" effect', } },
    azimuth_hood           = "Azimuth Hood +2",
    umuthi_hat             = "Umuthi Hat",
    merlinic_fastcast_head = { name = "Merlinic Hood", augments = { '"Mag.Atk.Bns."+20', '"Fast Cast"+7', 'INT+3', } },
    befouled_crown         = "Befouled Crown",
    amalric_coif           = "Amalric Coif +1",
    vanya_hood             = { name = "Vanya Hood", augments = { 'MND+10', 'Spell interruption rate down +15%', '"Conserve MP"+6', } },
    nyame_helm             = "Nyame Helm",
    atrophy_chapeau        = "Atro. Chapeau +3",
    mpacas_head            = "Mpaca's Cap",
    wakido_kabuto          = "Wakido Kabuto +3",
    ryuo_somen             = { name = "Ryuo Somen", augments = { 'HP+50', '"Store TP"+4', '"Subtle Blow"+7', } },
    mummu_head             = "Mummu Bonnet +2",
    Laksamas_tricorne      = "Laksa. Tricorne +4",
    bagua_galero           = "Bagua Galero",
    geo_galero             = "Geo. Galero +2",

    carmine_mask           = "Carmine Mask",
    sakpatas_helm          = "Sakpata's Helm",
    sakpatas_body          = "Sakpata's Plate",
    sakpatas_hands         = "Sakpata's Gauntlets",
    sakpatas_legs          = "Sakpata's Cuisses",
    sakpatas_feet          = "Sakpata's Leggings",

    arbatel_bonnet         = "Arbatel Bonnet +3",
    arbatel_gown           = "Arbatel Gown +3",
    arbatel_bracers        = "Arbatel Bracers +3",
    arbatel_pants          = "Arbatel Pants +3",
    arbatel_loafers        = "Arbatel Loafers +3",

    academics_bracers      = "Acad. Bracers +2",
    academics_loafers      = "Acad. Loafers +3",
    academics_mortarboard  = "Acad. Mortar. +2",
    academics_gown         = "Acad. Gown +2",
    academics_pants        = "Acad. Pants +2",


    pedagogy_mortarboard         = "Peda. Mortar. +4",
    pedagogy_gown                = "Pedagogy Gown +2",
    pedagogy_pants               = "Pedagogy Pants +1",
    pedagogy_loafers             = "Peda. Loafers",
    pedagogy_bracers             = "Peda. Bracers",

    kasuga_head                  = "Kasuga Kabuto +2",
    kasuga_body                  = "Kasuga Domaru +2",
    kasuga_hands                 = "Kasuga Kote +3",
    kasuga_legs                  = "Kasuga Haidate +2",
    kasuga_feet                  = "Kas. Sune-Ate +3",

    gletis_mask                  = "Gleti's Mask",
    gletis_body                  = "Gleti's Cuirass",
    gletis_hands                 = "Gleti's Gauntlets",
    gletis_legs                  = "Gleti's Breeches",
    gletis_feet                  = "Gleti's Boots",

    --body
    Adhemar_A_head               = { name = "Adhemar Bonnet +1", augments = { 'DEX+12', 'AGI+12', 'Accuracy+20', } },
    Adhemar_A_body               = { name = "Adhemar Jacket +1", augments = { 'DEX+12', 'AGI+12', 'Accuracy+20', } },
    mummu_jacket                 = "Mummu Jacket +2",
    pillagers_vest               = "Pillager's Vest +3",
    Laksamas_frac                = "Laksa. Frac +3",
    Lanun_frac                   = { name = "Lanun Frac +4", augments = { 'Enhances "Loaded Deck" effect', } },
    dread_jupon                  = "Dread Jupon",
    rawhide_vest                 = { name = "Rawhide Vest", augments = { 'DEX+10', 'STR+7', 'INT+7', } },
    meghanda_body                = "Meg. Cuirie +2",
    hashishin_mintan             = "Hashishin Mintan +3",
    malignance_tabard            = "Malignance Tabard",
    chironic_body_phalanx        = { name = "Chironic Doublet", augments = { 'Pet: INT+9', 'Phalanx +2', 'Accuracy+13 Attack+13', 'Mag. Acc.+6 "Mag.Atk.Bns."+6', } },
    body_phalanx                 = { name = "Merlinic Jubbah", augments = { 'Pet: DEX+5', 'Weapon Skill Acc.+4', 'Phalanx +4', 'Accuracy+8 Attack+8', 'Mag. Acc.+16 "Mag.Atk.Bns."+16', } },
    vitiation_tabard             = { name = "Viti. Tabard +4", augments = { 'Enhances "Chainspell" effect', } },
    oshosi_vest                  = "Oshosi Vest",
    Herc_MAB_vest                = { name = "Herculean Vest", augments = { 'Mag. Acc.+20 "Mag.Atk.Bns."+20', '"Mag.Atk.Bns."+15', } },
    atrophy_tabard               = "Atrophy Tabard +4",
    jhakri_cuffs                 = "Jhakri Cuffs +2",
    lethargy_body                = "Lethargy Sayon +3",
    passion_jacket               = "Passion Jacket",
    hjarrandi_breastplate        = "Hjarrandi Breast.",
    pummler_body                 = "Pumm. Lorica +4",
    Chasseurs_frac               = "Chasseur's Frac +2",
    boii_body                    = "Boii Lorica +3",
    assimilator_body             = "Assim. Jubbah +4",
    ea_houppe_p1                 = "Ea Houppe. +1",
    jhakri_robe                  = "Jhakri Robe +2",
    shango_robe                  = "Shango robe",
    nyame_mail                   = "Nyame Mail",
    ayanmo_corazza               = "Ayanmo Corazza +2",
    sakonji_body                 = "Sakonji Domaru +4",
    mpacas_body                  = "Mpaca's Doublet",
    dagon_breastplate            = "Dagon Breast.",
    merlinic_fastcast_body       = { name = "Merlinic Jubbah", augments = { '"Mag.Atk.Bns."+16', '"Fast Cast"+6', } },
    azimuth_coat                 = "Azimuth Coat +2",
    gyve_doublet                 = "Gyve Doublet",
    bagua_tunic                  = "Bagua Tunic",
    geomancy_tunic               = "Geomancy Tunic +2",

    --hands
    leyline_gloves               = { name = "Leyline Gloves", augments = { 'Accuracy+15', 'Mag. Acc.+15', '"Mag.Atk.Bns."+15', '"Fast Cast"+3', } },
    Chasseurs_hands              = "Chasseur's Gants +3",
    Adhemar_A_hands              = { name = "Adhemar Wrist. +1", augments = { 'DEX+12', 'AGI+12', 'Accuracy+20', } },
    meghan_golves                = "Meg. Gloves +2",
    malignance_gloves            = "Malignance Gloves",
    lethargy_hands               = "Leth. Ganth. +3",
    mummu_hands                  = "Mummu Wrists +2",
    carmine_gauntlets            = { name = "Carmine Fin. Ga.", augments = { 'Rng.Atk.+15', '"Mag.Atk.Bns."+10', '"Store TP"+5', } },
    hashishin_hands              = "Hashi. Bazu. +3",
    vitiation_gloves             = { name = "Viti. Gloves +4", augments = { 'Enhancing Magic duration', } },
    gazu_bracelets               = { name = "Gazu Bracelets +1", augments = { 'Path: A', } },
    ayanmo_hands                 = "Aya. Manopolas +2",
    atrophy_gloves               = "Atrophy Gloves +4",
    phalanx_hands                = { name = "Merlinic Dastanas", augments = { '"Store TP"+5', 'Sklchn.dmg.+4%', 'Phalanx +5', } },
    flama_hands                  = "Flam. Manopolas +2",
    boii_mufflers                = "Boii Mufflers +3",
    tatenashi_hands              = { name = "Tatena. Gote +1", augments = { 'Path: A', } },
    azimuth_gloves               = "Azimuth Gloves +2",
    chironic_refresh_gloves      = { name = "Chironic Gloves", augments = { '"Fast Cast"+1', 'Pet: VIT+4', '"Refresh"+1', 'Accuracy+12 Attack+12', } },
    nyame_hands                  = "Nyame Gauntlets",
    mpacas_gloves                = "Mpaca's Gloves",
    sakonji_kote                 = "Sakonji Kote +2",
    lanun_hands                  = "Lanun Gants +4",
    bagua_hands                  = "Bagua Mitaines",
    laksamas_hands               = "Lak. Gants +4",
    geo_mitaines                 = "Geo. Mitaines +2",

    --legs
    carmine_legs                 = { name = "Carmine Cuisses +1", augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6', } },
    Herc_TA_legs                 = { name = "Herculean Trousers", augments = { 'Accuracy+21', '"Triple Atk."+4', 'DEX+8', } },
    Herc_MAB_legs                = { name = "Herculean Trousers", augments = { 'Mag. Acc.+17 "Mag.Atk.Bns."+17', 'Weapon skill damage +2%', 'MND+1', '"Mag.Atk.Bns."+7', } },
    Herc_WS_legs                 = { name = "Herculean Trousers", augments = { 'Attack+17', 'Weapon skill damage +4%', } },
    laksamas_legs_cor_art        = "Laksa. Trews +3",
    megahan_legs                 = "Meg. Chausses +2",
    mummu_kecks                  = "Mummu Kecks +2",
    oshosi_legs                  = "Oshosi Trousers",
    desultor_tassets             = { name = "Desultor Tassets", augments = { '"Phantom Roll" ability delay -5', '"Waltz" TP cost -5', } },
    malignance_tights            = "Malignance Tights",
    hashishin_legs               = "Hashishin Tayt +3",
    tatenashi_legs               = { name = "Tatena. Haidate +1", augments = { 'Path: A', } },
    lethargy_legs                = "Leth. Fuseau +3",
    ayanmo_legs                  = "Aya. Cosciales +2",
    luhlaza_legs                 = { name = "Luhlaza Shalwar +4", augments = { 'Enhances "Assimilation" effect', } },
    odyssean_legs                = { name = "Odyssean Cuisses", augments = { 'Weapon skill damage +4%', 'DEX+4', } },
    boii_legs                    = "Boii Cuisses +3",
    Chasseurs_legs               = "Chas. Culottes +2",
    assimilator_legs             = "Assim. Shalwar +2",
    azimuth_tights               = "Azimuth Tights +2",
    atrophy_tights               = "Atrophy Tights +4",
    pummler_legs                 = "Pumm. Cuisses +3",
    jhakri_slops                 = "Jhakri Slops +2",
    shedir_seraweels             = 'Shedir Seraweels',
    psycloth_legs                = { name = "Psycloth Lappas", augments = { 'MP+80', 'Mag. Acc.+15', '"Fast Cast"+7', } },
    assiduity_pants              = "Assiduity pants +1",
    nyame_legs                   = "Nyame Flanchard",
    agwus_slops                  = "Agwu's Slops",
    hizamaru_legs                = "Hiza. Hizayoroi +2",
    wakido_legs                  = "Wakido Haidate +4",
    sakonji_legs                 = "Sakonji Haidate +2",
    mpacas_legs                  = "Mpaca's Hose",
    vitiation_tights             = "Viti. Tights +1",
    phalanx_legs                 = { name = "Merlinic Shalwar", augments = { 'Pet: "Dbl. Atk."+1', 'Enmity-3', 'Phalanx +5', 'Accuracy+10 Attack+10', 'Mag. Acc.+9 "Mag.Atk.Bns."+9', } },
    gyve_trousers                = "Gyve Trousers",
    bagua_pants                  = "Bagua Pants +3",
    geomancy_pants               = "Geomancy Pants +2", --15%
    volte_brais                  = "Volte Brais",
    Lanun_trews                  = "Lanun Trews +1",

    --feet
    malignance_boots             = "Malignance Boots",
    Herc_MAB_feet                = { name = "Herculean Boots", augments = { '"Mag.Atk.Bns."+13', 'Enmity-4', 'Mag. Acc.+18 "Mag.Atk.Bns."+18', } },
    Herc_TA_feet                 = { name = "Herculean Boots", augments = { 'Accuracy+21', '"Triple Atk."+4', 'Attack+12', } },
    Herc_WS_feet                 = { name = "Herculean Boots", augments = { 'Accuracy+25 Attack+25', 'Weapon skill damage +4%', 'Accuracy+14', } },
    mummu_feet                   = "Mummu Gamash. +2",
    Lanun_bottes                 = { name = "Lanun Bottes +4", augments = { 'Enhances "Wild Card" effect', } },
    pillagers_feet               = "Pill. Poulaines +2",
    Chasseurs_boots              = "Chass. Bottes +2",
    merlin_feet_burst            = { name = "Merlinic Crackows", augments = { 'Magic dmg. taken -5%', 'Pet: Haste+3', 'Magic burst dmg.+11%', 'Accuracy+1 Attack+1', 'Mag. Acc.+19 "Mag.Atk.Bns."+19', } },
    hashishin_feet               = "Hashi. Basmak +3",
    merlin_feet_phalanx          = { name = "Merlinic Crackows", augments = { 'Pet: Attack+7 Pet: Rng.Atk.+7', 'Mag. Acc.+15', 'Phalanx +4', 'Accuracy+17 Attack+17', 'Mag. Acc.+14 "Mag.Atk.Bns."+14', } },
    vitiation_boots              = { name = "Vitiation Boots +4", augments = { 'Immunobreak Chance', } },
    carmine_feet                 = { name = "Carmine Greaves +1", augments = { 'Accuracy+12', 'DEX+12', 'MND+20', } },
    oshosi_feet                  = "Oshosi Leggings",
    lethargy_feet                = "Leth. Houseaux +3",
    meghanda_feet                = "Meg. Jam. +2",
    hachiya_feet                 = "Hachiya Kyahan",
    luhlaza_feet                 = { name = "Luhlaza Charuqs +2", augments = { 'Enhances "Diffusion" effect', } },
    tatenashi_feet               = { name = "Tatena. Sune. +1", augments = { 'Path: A', } },
    taeon_dw_feet                = { name = "Taeon Boots", augments = { 'Accuracy+25', '"Dual Wield"+5', 'DEX+10', } },
    thereoid_greaves             = "Thereoid Greaves",
    sulevias_feet                = "Sulev. Leggings +2",
    agoge_feet                   = { name = "Agoge Calligae +1", augments = { 'Enhances "Tomahawk" effect', } },
    boi_feet                     = "Boii Calligae +2",
    mpacas_boots                 = "Mpaca's Boots",
    geo_sandals                  = "Geo. Sandals +3",
    hermes_sandals               = "Hermes' Sandals",
    pummler_feet                 = "Pumm. Calligae +3",
    merlinc_fastcast_feet        = { name = "Merlinic Crackows", augments = { '"Fast Cast"+5', 'INT+15', '"Mag.Atk.Bns."+4', } },
    heralds_gaiters              = "Herald's Gaiters",
    kaykaus_boots                = { name = "Kaykaus Boots", augments = { 'MP+60', 'Spell interruption rate down +10%', '"Cure" spellcasting time -5%', } },
    merlinic_refresh             = { name = "Merlinic Crackows", augments = { 'Crit.hit rate+1', '"Mag.Atk.Bns."+12', '"Refresh"+1', 'Accuracy+18 Attack+18', 'Mag. Acc.+16 "Mag.Atk.Bns."+16', } },
    nyame_feet                   = "Nyame Sollerets",
    mediums_sabots               = { name = "Medium's Sabots", augments = { 'MP+50', 'MND+8', '"Conserve MP"+6', '"Cure" potency +3%', } },
    valorous_feet_WS             = { name = "Valorous Greaves", augments = { 'Accuracy+28', 'Weapon skill damage +4%', 'AGI+2', 'Attack+10', } },
    telchine_feet_regen          = { name = "Telchine Pigaches", augments = { '"Regen" potency+3', } },
    Laksamas_boots               = "Laksa. Bottes +4",
    rawhide_boots_waltz          = "Rawhide Boots",
    bagua_sandals                = "Bagua Sandals +1",
    azimuth_feet                 = "Azimuth Gaiters +2",

    --neck pieces
    elite_royal_collar           = "Elite Royal Collar",
    loricate_torque              = { name = "Loricate Torque +1", augments = { 'Path: A', } },
    sanctity_necklace            = "Sanctity Necklace",
    sibyl_scarf                  = "Sibyl Scarf",
    caro_necklace                = "Caro Necklace",
    fotia_gorget                 = "Fotia Gorget",
    ocachi_gorget                = "Ocachi gorget",
    ainia_collar                 = "Ainia Collar",
    mirage_stole                 = { name = "Mirage Stole +2", augments = { 'Path: A', } },
    gaudryi_necklace             = "Gaudryi Necklace",
    republican_medal             = "Rep. Plat. Medal",
    ninja_nodowa                 = { name = "Ninja Nodowa +1", augments = { 'Path: A', } },
    null_loop                    = "Null Loop",
    commodore_charm              = { name = "Comm. Charm +1", augments = { 'Path: A', } },
    mizu_kubikazri               = "Mizu. Kubikazari",
    anu_torque                   = "Anu Torque",
    iskur_gorget                 = "Iskur Gorget",
    baetyl_pendant               = "Baetyl Pendant",
    vim_torque                   = { name = "Vim Torque +1", augments = { 'Path: A', } },
    warrior_beads                = { name = "War. Beads +1", augments = { 'Path: A', } },
    clotharius_torque            = "Clotharius Torque",
    saevus_pendant               = "Saevus Pendant +1",
    incanters_torque             = "Incanter's Torque",
    nodens_gorget                = 'Nodens Gorget',
    sams_nodowa                  = "Sam. Nodowa +1",
    warders_charm                = "Warder's Charm +1",
    malison_medallion            = "Malison Medallion",
    regal_necklace               = "Regal Necklace",
    mnk_nodowa                   = { name = "Mnk. Nodowa +1", augments = { 'Path: A', } },
    argute_stole                 = { name = "Argute Stole +2", augments = { 'Path: A', } },
    sroda_necklace               = "Sroda necklace",
    unmoving_collar              = "Unmoving Collar +1",
    quanpur_necklace             = "Quanpur Necklace",

    --waist
    platinum_moogle_belt         = "Plat. Mog. Belt",
    kentarch_belt_p1             = "Kentarch Belt +1",
    flume_belt                   = "Flume Belt",
    eschan_stone                 = "Eschan Stone",
    grunfeld_rope                = "Grunfeld Rope",
    orpheus_sash                 = "Orpheus's Sash",
    windbuffet_belt              = "Windbuffet Belt +1",
    sailfi_belt                  = { name = "Sailfi Belt +1", augments = { 'Path: A', } },
    yemaya_belt                  = "Yemaya Belt",
    hachirin_no_obi              = "Hachirin-no-Obi",
    luminary_sash                = "Luminary Sash",
    null_belt                    = "Null Belt",
    embla_sash                   = "Embla Sash",
    light_belt                   = "Light Belt",
    gishdubar_sash               = "Gishdubar sash",
    reiki_yotai                  = "Reiki Yotai",
    witful_belt                  = "Witful Belt",
    refoccilation_stone          = "Refoccilation Stone",
    emphatikos_rope              = "Emphatikos Rope",
    olympus_sash                 = "Olympus Sash",
    moonbow_belt                 = "Moonbow Belt +1",
    cornelias_belt               = "Cornelia's Belt",
    ask_sash                     = "Ask Sash",
    chaac_belt                   = "Chaac Belt",
    siegel_sash                  = "Siegel Sash",
    fotia_belt                   = "Fotia Belt",
    aasklepian_belt              = "Asklepian Belt",
    acuity_belt                  = "Acuity Belt +1",
    isa_belt                     = "Isa Belt",

    --back
    COR_TP_Cape                  = { name = "Camulus's Mantle", augments = { 'AGI+20', 'Rng.Acc.+20 Rng.Atk.+20', '"Store TP"+10', } },
    COR_WS1_Cape                 = { name = "Camulus's Mantle", augments = { 'AGI+20', 'Mag. Acc+20 /Mag. Dmg.+20', 'AGI+10', 'Weapon skill damage +10%', } },
    COR_WS2_Cape                 = { name = "Camulus's Mantle", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', 'Weapon skill damage +10%', } },
    THF_TP_Cape                  = { name = "Toutatis's Cape", augments = { 'DEX+20', 'Accuracy+20 Attack+20', '"Store TP"+10', } },
    THF_WS_crit_cape             = { name = "Toutatis's Cape", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'Crit.hit rate+10', } },
    RDM_DW_Cape                  = { name = "Sucellos's Cape", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'DEX+10', '"Dual Wield"+10', 'Phys. dmg. taken-10%', } },
    RDM_SAV_Cape                 = { name = "Sucellos's Cape", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', 'Weapon skill damage +10%', } },
    RDM_Crit_Cape                = { name = "Sucellos's Cape", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'DEX+10', 'Crit.hit rate+10', } },
    RDM_MAB_Cape                 = { name = "Sucellos's Cape", augments = { 'INT+20', 'Mag. Acc+20 /Mag. Dmg.+20', 'INT+10', '"Mag.Atk.Bns."+10', } },
    RDM_ENHANCHING_DURATION_CAPE = { name = "Ghostfyre Cape", augments = { 'Enfb.mag. skill +1', 'Enha.mag. skill +8', 'Enh. Mag. eff. dur. +20', } },
    exp_back                     = { name = "Mecisto. Mantle", augments = { 'Cap. Point+35%', 'HP+16', 'Mag. Acc.+3', 'DEF+5', } },
    BLU_TP_Cape                  = { name = "Rosmerta's Cape", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'Accuracy+10', '"Store TP"+10', 'Phys. dmg. taken-10%', } },
    BLU_SAV_WS_CAPE              = { name = "Rosmerta's Cape", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', 'Weapon skill damage +10%', } },
    BLU_CRIT_WS_CAPE             = { name = "Rosmerta's Cape", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'DEX+10', 'Crit.hit rate+10', } },
    BLU_CURE_CAPE                = { name = "Rosmerta's Cape", augments = { 'MND+20', '"Cure" potency +10%', 'Phys. dmg. taken-10%', } },
    BLU_SKILL_CAPE               = { name = "Cornflower Cape", augments = { 'MP+24', 'DEX+3', 'Accuracy+3', 'Blue Magic skill +10', } },
    toro_cape                    = "Toro Cape",
    NIN_WSD_Cape                 = { name = "Andartia's Mantle", augments = { 'Weapon skill damage +7%', } },
    null_shawl                   = "Null Shawl",
    WAR_SAV_WS_CAPE              = { name = "Cichol's Mantle", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', 'Weapon skill damage +10%', } },
    WAR_TP_DT_CAPE               = { name = "Cichol's Mantle", augments = { 'DEX+20', 'Accuracy+20 Attack+20', '"Store TP"+10', 'Phys. dmg. taken-10%', } },
    swith_cape                   = "Swith Cape",
    SCH_MAB_CAPE                 = { name = "Lugh's Cape", augments = { 'INT+20', 'Mag. Acc+20 /Mag. Dmg.+20', 'INT+10', '"Mag.Atk.Bns."+10', } },
    SCH_FASTCAST_CAPE            = { name = "Lugh's Cape", augments = { '"Fast Cast"+10', } },
    SAM_WS_CAPE                  = { name = "Smertrios's Mantle", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', 'Weapon skill damage +10%', } },
    SAM_TP_CAPE_DT               = { name = "Smertrios's Mantle", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'Accuracy+10', '"Store TP"+10', 'Phys. dmg. taken-10%', } },
    MNK_TP_CAPE                  = { name = "Segomo's Mantle", augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'Accuracy+3', '"Dbl.Atk."+10', 'Damage taken-5%', } },
    oretan_cape                  = "Oretan. Cape +1",
    SCH_HELX_REGEN_CAPE          = { name = "Bookworm's Cape", augments = { 'INT+4', 'MND+2', '"Regen" potency+10', } },
    MNK_CRT_CAPE                 = { name = "Segomo's Mantle", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', 'Crit.hit rate+10', } },
    MNK_DA_STR_CAPE              = { name = "Segomo's Mantle", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+10', '"Dbl.Atk."+10', 'System: 1 ID: 640 Val: 4', } },
    argocham_mantle              = "Argocham. Mantle",
    GEO_CAPE                     = { name = "Nantosuelta's Cape", augments = { 'HP+60', 'Eva.+20 /Mag. Eva.+20', 'Mag. Evasion+10', 'Pet: "Regen"+10', 'Pet: "Regen"+5', } },
    lifestream_cape              = { name = "Lifestream Cape", augments = { 'Geomancy Skill +10', 'Indi. eff. dur. +13', 'Pet: Damage taken -2%', } },

    -- earrings
    suppanomimi                  = "Suppanomimi",
    dedition_earring             = "Dedition Earring",
    enervating_earrng            = "Enervating Earring",
    friomisi_earring             = "Friomisi Earring",
    sortiarius_earring_mab6      = "Sortiarius Earring",
    odr_earring                  = "Odr Earring",
    moonshade_earring            = { name = "Moonshade Earring", augments = { 'Accuracy+4', 'TP Bonus +250', } },
    halasz_earring               = "Halasz Earring",
    crepus_earring               = "Crep. Earring",
    sherida_earring              = "Sherida Earring",
    ishvara                      = "Ishvara Earring",
    hashishin_earring            = { name = "Hashi. Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+11', 'Mag. Acc.+11', '"Dbl.Atk."+3', } },
    earthcry_earring             = "Earthcry Earring",
    malignance_earring           = "Malignance Earring",
    njordr_earring               = "Njordr Earring",
    lugra_earring                = { name = "Lugra Earring +1", augments = { 'Path: A', } },
    brutal_earring               = "Brutal Earring",
    eabani_earring               = "Eabani Earring",
    lethargy_earring             = { name = "Leth. Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+11', 'Mag. Acc.+11', '"Dbl.Atk."+3', } },
    snorta_earring               = "Snotra Earring",
    mache_earring_p1             = "Mache Earring +1",
    boii_earring                 = { name = "Boii Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+12', 'Mag. Acc.+12', 'Crit.hit rate+4', } },
    thrud_earring                = "Thrud Earring",
    odnowa_earring               = "Odnowa Earring",
    schere_earring               = "Schere Earring",
    alabaster_earring            = "Alabaster Earring",
    loquacious_earring           = "Loquac. Earring",
    barkaro_earring              = "Barkaro. Earring",
    mimir_earring                = "Mimir Earring",
    andoaa_earring               = "Andoaa Earring",
    static_earring               = "Static Earring",
    lugalbanda_earring           = "Lugalbanda Earring",
    mendicants_earring           = "Mendicant's earring",
    skulkers_earring             = { name = "Skulk. Earring +2", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+20', 'Mag. Acc.+20', '"Store TP"+8', 'DEX+15 AGI+15', } },
    kasuga_earring               = "Kasuga Earring +1",
    bhikku_earring               = { name = "Bhikku Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+13', 'Mag. Acc.+13', '"Store TP"+4', } },
    regal_earring                = "Regal Earring",
    etiolation_earring           = "Etiolation Earring",
    arbatel_earring              = { name = "Arbatel Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Mag. Acc.+12', 'Enmity-2', } },
    beyla_earring                = "Beyla Earring",
    chevaliers_earring           = { name = "Chev. Earring +1", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+13', 'Mag. Acc.+13', 'Damage taken-4%', } },
    azimuth_earring              = "Azimuth Earring +1",

    --rings
    gelat_ring_pdt               = "Gelatinous Ring +1",
    kishar_ring                  = "Kishar Ring",
    corneilias_ring              = "Cornelia's Ring",
    rajas_ring                   = "Rajas Ring",
    eponas_ring                  = "Epona's Ring",
    acumen_ring_mab4             = "Acumen Ring",
    mummu_ring                   = "Mummu Ring",
    crepuscular_ring             = "Crepuscular Ring",
    stikini_ring                 = { name = "Stikini Ring", bag = 'wardrobe5' },
    stikini_ring2                = { name = "Stikini Ring", bag = 'wardrobe6' },
    defending_ring               = "Defending Ring",
    petrov_ring                  = "Petrov Ring",
    bataria_ring_cor_poten       = "Barataria Ring",
    apate_ring                   = "Apate Ring",
    dingir_ring                  = "Dingir Ring",
    metamorph_ring               = { name = "Metamor. Ring +1", augments = { 'Path: A', } },
    chirich_ring                 = "Chirich Ring +1",
    cacoethic_ring               = { name = "Cacoethic Ring +1", augments = { 'Path: A', } },
    freke_ring                   = "Freke Ring",
    epaminondas_ring             = "Epaminondas's Ring",
    weatherspoon_ring            = "Weather. Ring",
    gere_ring                    = "Gere Ring",
    mujin_band                   = "Mujin Band",
    ilabrat_ring                 = 'Ilabrat ring',
    begrudging_ring              = "Begrudging Ring",
    niqmaddu_ring                = "Niqmaddu Ring",
    najis_loop                   = "Naji's Loop",
    lebeche_ring                 = "Lebeche Ring",
    acrchon_ring                 = "Archon Ring",
    menelaus_ring                = "Menelaus's Ring",
    mallquis_ring                = "Mallquis Ring",
    murky_ring                   = "Murky Ring",
    asklepian_ring               = "Asklepian Ring",
    hoxne_ring                   = "Hoxne Ring",

    --weapons
    naegling                     = "Naegling",
    nuku_shield                  = "Nusku Shield",
    doomsday                     = { name = "Doomsday", augments = { '"Mag.Atk.Bns."+20', 'Weapon skill damage +5%', 'AGI+21', } },
    tauret                       = "Tauret",
    demersal_degen               = { name = "Demers. Degen +1", augments = { 'Path: A', } },
    maxentius                    = "Maxentius",
    daybreak                     = "Daybreak",
    ullr                         = "Kaja Bow",
    gletis_knife                 = "Gleti's Knife",
    blurred_shield               = "Blurred Shield +1",
    crocea_mors                  = { name = "Crocea Mors", augments = { 'Path: C', } },
    pukulatmuj_1                 = { name = "Pukulatmuj +1", augments = { 'Path: A', } },
    levante_dagger               = "Levante Dagger",
    sakpatas_sword               = "Sakpata's Sword",
    forfend_p1                   = "Forfend +1",
    bunzi_rod                    = "Bunzi's Rod",
    colada_phalanx               = { name = "Colada", augments = { 'MND+7', 'DEX+9', 'Phalanx +3', } },
    molybdosis                   = "Molybdosis",
    ammurapi_shield              = "Ammurapi Shield",
    culminus                     = 'Culminus',
    pedagogy_staff               = { name = "Pedagogy Staff", augments = { 'Path: C', } },
    enki_strap                   = "Enki Strap",
    genbus_shield                = "Genbu's Shield",
    fomalhaut                    = "Fomalhaut",
    death_penalty                = "Death Penalty",
    solstice                     = { name = "Solstice", augments = { 'INT+15', '"Mag.Atk.Bns."+10', '"Refresh"+1', } },

    --ammo
    oshashs_treastise            = "Oshasha's Treatise",
    sroda_tathlum                = "Sroda Tathlum",
    aurgelmir_orb                = "Aurgelmir Orb",
    staunch_tathlum              = "Staunch Tathlum",
    ghastly_tathlum              = { name = "Ghastly Tathlum +1", augments = { 'Path: A', } },
    sapience_orb                 = "Sapience Orb", --2% fast cast
    coiste_bodhar                = { name = "Coiste Bodhar", augments = { 'Path: A', } },
    knobkierrie                  = "Knobkierrie",
    yetshila                     = "Yetshila",
    hydrocera                    = "Hydrocera",
    crepuscular_pebble           = "Crepuscular Pebble",
    homiliary                    = "Homiliary",
    amar_cluster                 = "Amar Cluster",
    perfect_lucky_egg            = "Per. Lucky Egg",
    dunna                        = "Dunna"
}
return equipment
