---@diagnostic disable: undefined-global
-- Gear inventory for Poquito
-- Returns a table of gear pieces referenced across job files

return {
    -- Range / Ammo
    Miracle_Cheer      = "Miracle Cheer",
    Matre_Bell         = "Matre Bell",
    Hangaku_no_Yumi    = "Hangaku-no-Yumi",
    Mavi_Tathlum       = "Mavi Tathlum",
    Knobkierrie        = "Knobkierrie",
    Ginsen             = "Ginsen",
    Relic_Horn         = "Relic Horn",

    -- Sub
    Kali               = { name = "Kali", augments = { 'Mag. Acc.+15', 'String instrument skill +10', 'Wind instrument skill +10', } },
    Naegling           = "Naegling",
    Nibiru_Cudgel      = "Nibiru Cudgel",
    Kaja_Rod           = "Kaja Rod",
    Enki_Strap         = "Enki Strap",
    Adapa_Shield       = "Adapa Shield",
    Choco_Shield       = "Choco. Shield +1",
    Genmei_Shield      = "Genmei Shield",

    -- Head
    Fili_Calot         = "Fili Calot +2",
    Inyanga_Tiara      = "Inyanga Tiara +2",
    Aya_Zucchetto      = "Aya. Zucchetto +1",
    Vanya_Hood         = { name = "Vanya Hood", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Tema_Headband      = "Tema. Headband",
    Merl_Hood          = "Merlinic Hood",
    Decennial_Crown    = "Decennial Crown",
    Redeyes            = "Redeyes",
    Bards_Roundlet     = "Bard's Roundlet",
    Brioso_Roundlet    = "Brioso Roundlet +2",
    Choral_Roundlet    = "Choral Roundlet",
    Behemoth_Masque    = "Behemoth Masque",
    Goblin_Masque      = "Goblin Masque",
    GMoogle_Masque     = "G. Moogle Masque",

    -- Neck
    Moonbow_Whistle    = "Moonbow Whistle",
    Aoidos_Matinee     = "Aoidos' Matinee",
    Bards_Charm        = { name = "Bard's Charm +1", augments = { 'Path: A', } },
    Loricate_torque    = "Loricate Torque +1",
    Quanpur_Necklace   = "Quanpur Necklace",
    Adad_Amulet        = "Adad Amulet",
    Erra_Pendant       = "Erra Pendant",
    Mizu_Kubikazari    = "Mizu. Kubikazari",

    -- Ear
    Raising_Earring    = "Raising Earring",
    Dominance_Earring  = "Dominance Earring",
    Brutal_Earring     = "Brutal Earring",
    Alabaster_Earring  = "Alabaster Earring",
    Loquac_Earring     = "Loquac. Earring",
    Skulkers_Earring   = { name = "Skulker's Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+8', 'Mag. Acc.+8', } },
    Hattori_Earring    = { name = "Hattori Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+8', 'Mag. Acc.+8', } },
    Nourish_Earring    = "Nourish. Earring",
    Ebers_Earring      = { name = "Ebers Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+8', 'Mag. Acc.+8', } },
    Erilaz_Earring     = { name = "Erilaz Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+7', 'Mag. Acc.+7', } },
    Erilaz_Earring_6   = { name = "Erilaz Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+6', 'Mag. Acc.+6', } },
    Boii_Earring       = { name = "Boii Earring", augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+6', 'Mag. Acc.+6', } },
    Eabani_Earring     = "Eabani Earring",

    -- Body
    Fili_Hongreline    = "Fili Hongreline +1",
    Inyanga_Jubbah     = "Inyanga Jubbah +2",
    Ayanmo_Corazza     = "Ayanmo Corazza +1",
    Vanya_Robe         = { name = "Vanya Robe", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Merl_Jubbah        = "Merlinic Jubbah",
    Bihu_Jstcorps      = { name = "Bihu Jstcorps. +3", augments = { 'Enhances "Troubadour" effect', } },
    Brioso_Just        = "Brioso Justau. +2",
    WN_Kaftan          = "WN Kaftan +1",
    Terminal_Plate     = "Terminal Plate",
    Temachtiani_Shirt  = "Temachtiani Shirt",
    Novennial_Coat     = "Novennial Coat",
    Decennial_Coat     = "Decennial Coat",
    Behemoth_Suit      = "Behemoth Suit",
    Goblin_Suit        = "Goblin Suit",
    GMoogle_Suit       = "G. Moogle Suit",

    -- Hands
    Fili_Manchettes    = "Fili Manchettes +2",
    Inyanga_Dastanas   = "Inyan. Dastanas +2",
    Aya_Manopolas      = "Aya. Manopolas +1",
    Vanya_Cuffs        = { name = "Vanya Cuffs", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Bihu_Cuffs         = { name = "Bihu Cuffs", augments = { 'Enhances "Con Brio" effect', } },
    Merl_Dastanas      = "Merlinic Dastanas",
    Brioso_Cuffs       = "Brioso Cuffs +3",
    Viti_Gloves        = { name = "Viti. Gloves +3", augments = { 'Enhancing Magic duration', } },
    Choral_Cuffs       = "Choral Cuffs",
    WN_Mittens         = "WN Mittens +1",
    Gende_Gages        = "Gende. Gages +1",
    Temachtiani_Gloves = "Temachtiani Gloves",
    Leyline_Gloves     = { name = "Leyline Gloves", augments = { 'Accuracy+6', 'Mag. Acc.+2', '"Mag.Atk.Bns."+6', } },

    -- Rings
    Dim_Ring_Dem       = "Dim. Ring (Dem)",
    Inyanga_Ring       = "Inyanga Ring",
    Jubilee_Ring       = "Jubilee Ring",
    Echad_Ring         = "Echad Ring",
    Facility_Ring      = "Facility Ring",
    Warp_Ring          = "Warp Ring",
    Apate_Ring         = "Apate Ring",
    Caliber_Ring       = "Caliber Ring",
    Kishar_Ring        = "Kishar Ring",
    Empress_Band       = "Empress Band",
    Murky_Ring         = "Murky Ring",
    Shneddick_Ring     = "Shneddick Ring",

    -- Back
    Intarabus_Cape_DT  = { name = "Intarabus's Cape", augments = { 'HP+30', 'Eva.+10 /Mag. Eva.+10', '"Cure" potency +10%', 'Phys. dmg. taken-2%', } },
    Intarabus_Cape_FC  = { name = "Intarabus's Cape", augments = { '"Fast Cast"+10', } },
    Intarabus_Cape_WS  = { name = "Intarabus's Cape", augments = { 'STR+20', 'Accuracy+20 Attack+20', 'STR+5', 'Weapon skill damage +10%', } },
    Nexus_Cape         = "Nexus Cape",
    Mauler_Mantle      = "Mauler's Mantle",
    Dispersal_Mantle   = "Dispersal Mantle",
    Alabaster_Mantle   = "Alabaster Mantle",

    -- Waist
    Olympus_Sash       = "Olympus Sash",
    Flume_Belt         = "Flume Belt",
    Embla_Sash         = "Embla Sash",
    Sailfi_Belt        = "Sailfi Belt +1",
    Harfners_Sash      = "Harfner's Sash",

    -- Legs
    Fili_Rhingrave     = "Fili Rhingrave +1",
    Inyanga_Shalwar    = "Inyanga Shalwar +2",
    Aya_Cosciales      = "Aya. Cosciales +2",
    Vanya_Slops        = { name = "Vanya Slops", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Hercl_Trousers     = "Herculean Trousers",
    Bards_Cannions     = "Bard's Cannions",
    Brioso_Cannions    = "Brioso Cannions +2",
    Assid_Pants        = "Assid. Pants +1",
    Bihu_Cannions      = { name = "Bihu Cannions", augments = { 'Enhances "Soul Voice" effect', } },
    Choral_Cannions    = "Choral Cannions",
    WN_Braccae         = "WN Braccae +1",
    Temachtiani_Pants  = "Temachtiani Pants",
    Avatara_Slops      = "Avatara Slops",
    Sorcerer_Tonban    = "Sorcerer's Tonban",
    Estqr_Fuseau       = "Estqr. Fuseau +1",
    Novennial_Hose     = "Novennial Hose",
    Decennial_Tights   = "Decennial Tights",

    -- Feet
    Inyanga_Crackows   = "Inyan. Crackows +1",
    Aya_Gambieras      = "Aya. Gambieras +1",
    Vanya_Clogs        = { name = "Vanya Clogs", augments = { 'MP+50', '"Cure" potency +7%', 'Enmity-6', } },
    Merl_Crackows      = "Merlinic Crackows",
    Brioso_Slippers    = "Brioso Slippers +3",
    Bihu_Slippers      = { name = "Bihu Slippers", augments = { 'Enhances "Nightingale" effect', } },
    Bards_Slippers     = "Bard's Slippers",
    Choral_Slippers    = "Choral Slippers",
    Fili_Cothurnes     = "Fili Cothurnes +2",
    WN_Clomps          = "WN Clomps +1",
    Temachtiani_Boots  = "Temachtiani Boots",
    Odyssean_Greaves   = "Odyssean Greaves",
    Melee_Gaiters      = "Melee Gaiters",
    Abyss_Sollerets    = "Abyss Sollerets",
    Sprinters_Shoes    = "Sprinter's Shoes",
}
